version: "3.8"


services:
  mongodb:
    image: mongo
    container_name: mongo-userdetails
    environment:
      - PUID=1000
      - PGID=1000
#    volumes:
#      - ./mongodb/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.10-management
    container_name: rabbitmq.mongo
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./dados:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin